stages:
  - package
  - build
  - push

build_image:
  stage: build
  script:
    - docker build -t erddap-axiom:$CI_BUILD_REF_NAME .

test:
  stage: test
  image: maven:3
  script: mvn -Dtest=RunAllUnitTests test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

push_master:
  stage: push
  only:
    - master
  script:
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:latest
    - docker push registry.axiom/erddap-axiom:latest

push_branch:
  stage: push
  only:
    - branches
  except:
    - master
  script:
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:$CI_BUILD_REF_NAME
    - docker push registry.axiom/erddap-axiom:$CI_BUILD_REF_NAME

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:$CI_BUILD_TAG
    - docker push registry.axiom/erddap-axiom:$CI_BUILD_TAG
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:prod
    - docker push registry.axiom/erddap-axiom:prod
