stages:
  - package
  - build
  - push

build_image:
  stage: build
  script:
    - docker build -t erddap-axiom:$CI_BUILD_REF_NAME .

push_master:
  stage: push
  only:
    - master
  script:
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:latest
    - docker push registry.axiom/erddap-axiom:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:$CI_BUILD_TAG
    - docker push registry.axiom/erddap-axiom:$CI_BUILD_TAG
    - docker tag erddap-axiom:$CI_BUILD_REF_NAME registry.axiom/erddap-axiom:prod
    - docker push registry.axiom/erddap-axiom:prod
